//------------------------------------------------------------------------------
// <auto-generated>
//	 This code was generated by a tool.
//	 Runtime Version:4.0.30319.42000
//
//	 Changes to this file may cause incorrect behavior and will be lost if
//	 the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LogService.Localisation {
	using System;
	
	
	/// <summary>
	///   A strongly-typed resource class, for looking up localized strings, etc.
	/// </summary>
	// This class was auto-generated by the StronglyTypedResourceBuilder
	// class via a tool like ResGen or Visual Studio.
	// To add or remove a member, edit your .ResX file then rerun ResGen
	// with the /str option, or rebuild your VS project.
	[global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
	[global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
	[global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
	public class LogMessageLoc {
		
		private static global::System.Resources.ResourceManager resourceMan;
		
		private static global::System.Globalization.CultureInfo resourceCulture;
		
		[global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
		internal LogMessageLoc() {
		}
		
		/// <summary>
		///   Returns the cached ResourceManager instance used by this class.
		/// </summary>
		[global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
		public static global::System.Resources.ResourceManager ResourceManager {
			get {
				if (object.ReferenceEquals(resourceMan, null)) {
					global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LogService.Localisation.LogMessageLoc", typeof(LogMessageLoc).Assembly);
					resourceMan = temp;
				}
				return resourceMan;
			}
		}
		
		/// <summary>
		///   Overrides the current thread's CurrentUICulture property for all
		///   resource lookups using this strongly typed resource class.
		/// </summary>
		[global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
		public static global::System.Globalization.CultureInfo Culture {
			get {
				return resourceCulture;
			}
			set {
				resourceCulture = value;
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to Category.
		/// </summary>
		public static string Category {
			get {
				return ResourceManager.GetString("Category", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to Date and time.
		/// </summary>
		public static string DateTime {
			get {
				return ResourceManager.GetString("DateTime", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to Exception.
		/// </summary>
		public static string Exception {
			get {
				return ResourceManager.GetString("Exception", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to Level.
		/// </summary>
		public static string LogLevel {
			get {
				return ResourceManager.GetString("LogLevel", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to Log message.
		/// </summary>
		public static string LogMessage {
			get {
				return ResourceManager.GetString("LogMessage", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to Log messages.
		/// </summary>
		public static string LogMessages {
			get {
				return ResourceManager.GetString("LogMessages", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to Message.
		/// </summary>
		public static string Message {
			get {
				return ResourceManager.GetString("Message", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to Raw message.
		/// </summary>
		public static string RawMessage {
			get {
				return ResourceManager.GetString("RawMessage", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to Source.
		/// </summary>
		public static string Source {
			get {
				return ResourceManager.GetString("Source", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to State.
		/// </summary>
		public static string State {
			get {
				return ResourceManager.GetString("State", resourceCulture);
			}
		}
	}
}
